# Generated by Django 4.1 on 2022-09-12 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='videos.category')),
            ],
        ),
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(max_length=600, verbose_name='شرح')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان تولید')),
                ('jalali_created', django_jalali.db.models.jDateField(auto_now_add=True, null=True, verbose_name='زمان تولید فارسی')),
                ('jalali_updated', django_jalali.db.models.jDateField(auto_now=True, null=True, verbose_name='به روز شده ')),
                ('cover_image', models.ImageField(null=True, upload_to='images/video-images', verbose_name='تصویر کاور ویدیو')),
                ('video', models.FileField(null=True, upload_to='videos', verbose_name='ویدیو')),
                ('allowing', models.BooleanField(default=False, verbose_name='مجاز')),
                ('slug', django_extensions.db.fields.AutoSlugField(allow_unicode=True, blank=True, editable=False, populate_from=['title'], unique=True, verbose_name='آدرس')),
                ('category', models.ManyToManyField(to='videos.category', verbose_name='دسته بندی')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='')),
                ('hits', models.ManyToManyField(blank=True, related_name='hits', to='videos.ipaddress', verbose_name='بازدید')),
            ],
            options={
                'verbose_name': 'ویدیو',
                'verbose_name_plural': 'ویدیو ها',
                'ordering': ('-created_at',),
            },
        ),
    ]
