# Generated by Django 4.1 on 2022-09-25 15:10

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_time',), 'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AddField(
            model_name='comment',
            name='jalali_created',
            field=django_jalali.db.models.jDateField(auto_now_add=True, null=True, verbose_name='زمان تولید فارسی'),
        ),
    ]
