# Generated by Django 4.1 on 2022-10-12 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0006_alter_comment_options_comment_jalali_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField()),
                ('category', models.CharField(max_length=10)),
                ('notification_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('jalali_created', django_jalali.db.models.jDateField(auto_now_add=True, null=True, verbose_name='زمان تولید فارسی')),
                ('post_id', models.IntegerField(default=-1)),
                ('n_count', models.PositiveIntegerField(default=0)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
