# Generated by Django 4.1 on 2022-12-02 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userfollowing'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollowing',
            name='following',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userfollowing',
            name='following_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='کابر دنبال کننده'),
        ),
    ]
