# Generated by Django 4.1 on 2022-12-02 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userfollowing_following_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollowing',
            old_name='following',
            new_name='its_following',
        ),
    ]
