# Generated by Django 4.1 on 2022-09-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_bio_user_github_user_image_user_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=['email'], max_length=50, unique=True, verbose_name='نام کاربری'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='درباره'),
        ),
    ]
