# Generated by Django 4.1 on 2022-09-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200, verbose_name='آدرس')),
                ('support', models.CharField(max_length=15, verbose_name='پشتیبانی')),
                ('email', models.EmailField(max_length=250, verbose_name='آدرس ایمیل')),
                ('instagram', models.URLField(blank=True, verbose_name='آیدی اینستاگرام')),
                ('telegram', models.URLField(blank=True, verbose_name='آدرس تلگرام')),
                ('whatsapp', models.URLField(blank=True, verbose_name='آدرس واتساپ')),
                ('twitter', models.URLField(blank=True, verbose_name='آدرس تویتر')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'اطلاعات تماس',
            },
        ),
    ]
