# Generated by Django 4.1 on 2022-09-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contactinfo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='allowing',
            field=models.BooleanField(default=False),
        ),
    ]
